### ISSUE TITLE
Notify user of incoming Audio/Video Call

### ISSUE THREAD

**Issue by sidmurali0885** [DreamTeamMobile/Xamarin.Agora.Samples#1]
Hi. Is it possible to notify the user of an incoming video or audio call. Similar to an incoming phone or face time call. Is this something that can be achieved with this product?

**Comment by alexsorokoletov** [comment]
Hi @sidmurali0885.
You would need to use integration with CallKit on iOS and ConnectionService on Android

**Comment by sidmurali0885** [comment]
Thanks for the information. Can you point me to any documentation or sample
code to implement this?

Thanks for your help!

Thanks and Regards,
*Siddharth Murali*

**Comment by alexsorokoletov** [comment]
Siddharth, search for SpeakerBox from Apple. As for Android, just search for “ConnectionService Android”. Don’t have anything specific in mind for Android. 

Alex

**Comment by AbuMandour** [comment]
@sidmurali0885 do you reach any documentation or solution to do that ?

**Comment by softsan** [comment]
@sidmurali0885  I have implemented iOS CallKit using Twilio in Xamarin: https://medium.com/@san.thanki/callkit-pushkit-twilio-with-xamarin-83553f93be86 it is not with Agora but may be helpful on direction on how to achieve it using CallKit
