### ISSUE TITLE
iOS RemoteView problem.

### ISSUE THREAD

**Issue by felipecds** [DreamTeamMobile/Xamarin.Agora.Samples#13]
I'm having some problem with the remote view. The remote user connect without problems, but only his video is not showing. I can hear it without no problems. 

On android, both remote and local view shows without no problem.

Using ios 13, xamarin 4.3+.

**Comment by alexsorokoletov** [comment]
Hi @felipecds!
There is a sample for Xamarin (Native) and another one for Xamarin.Forms.
Which sample exactly are you using?

**Comment by felipecds** [comment]
I’m using a modified version of Xamarin.Forms sample, it’s implemented on my app.

But yesterday I found the solution, but I don’t know if it’s a general problem. Only in iOS, if I use a layout with Horizontal and Vertical options to FillAndExpand, only in iOS the remote view didn’t show. In Android, the remote view works.

I changed to AbsoluteLayout, and forces a 1,1 proportion on the view, and work in both platforms.

[cid:image001.jpg@01D61A10.A1DA8560]

return new Contact()
{
Name = "Felipe Pedroti Raymundo",
       Role = "Analista/Desenvolvedor Full Stack",
       OfficePhone = "+55 (43) 3524-3344",
       WebSite = "www.cds-software.com.br<http://www.cds-software.com.br/>",
       LinkedIn = "https://www.linkedin.com/company/cds---software/",
Blog = " https://blogdosistema.com.br/"
};

**Comment by AhmedTaha0** [comment]
I have a problem while using Xamarin.Agora.Full.Forms. It works well in everything except when I need to render the local video above the remote video using Absolute Layout. The local video can't be rendered however it render only when the 2 videos are under each other whatever using grid or stacklayout. So could you please tell me why this behaviour happen and how to solve this problem

**Comment by alexsorokoletov** [comment]
@AhmedTaha0 if you still have the problem please open separate thread.
