### ISSUE TITLE
Xamarin nuget package for latest Agroa 3.0.1.1

### ISSUE THREAD

**Issue by softsan** [DreamTeamMobile/Xamarin.Agora.Samples#14]
Hi,

Agora has release 3.0.1.1 so when this will be available for Xamarin?

https://docs.agora.io/en/Video/release_ios_video?platform=iOS#v3011
https://docs.agora.io/en/Video/release_android_video?platform=Android#v3011

Thanks.

**Comment by alexsorokoletov** [comment]
Thank you, @softsan.
We roll out updates usually the same or next week

Please check pre-releases available on Nuget https://www.nuget.org/packages/Xamarin.Agora.Full.iOS/3.1.3-beta14
