### ISSUE TITLE
Overlapping video views doesn't work

### ISSUE THREAD

**Issue by tendaimaswaya** [DreamTeamMobile/Xamarin.Agora.Samples#29]
Whilst i can get the video to work, it seems in the scenario where one wants to overlap videos and place one view on top of the other, the other view will completely dissappear. What could be happening here?

**Comment by alexsorokoletov** [comment]
Hi @tendaimaswaya!
Probably something along these lines: https://stackoverflow.com/a/40011666

This is a common issue with Android apps (not specific to Agora)

**Comment by tendaimaswaya** [comment]
Thanks @alexsorokoletov , indeed it is.
