### ISSUE TITLE
I need sample for text chat using Signaling sdk

### ISSUE THREAD

**Issue by prasannamca1107** [DreamTeamMobile/Xamarin.Agora.Samples#5]
i found the xamarin nuget but i can't find any sample for xamarin or xamrin forms 

Xamarin.Agora.Signaling.iOS 
Xamarin.Agora.Signaling.Android

**Comment by alexsorokoletov** [comment]
@prasannamca1107 these NuGet packages are obsolete/old, thanks for pointing this out!

Agora now has a new product called Agora RTM https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=All%20Platforms

These are the packages you should use now:
https://www.nuget.org/packages/Xamarin.Agora.Rtm.Android/
https://www.nuget.org/packages/Xamarin.Agora.Rtm.iOS/

There is no specific documentation for Xamarin, however, you can follow iOS/Android tutorials and just translate same API calls into C#.

Hope that helps.
