### ISSUE TITLE
how make call with proxy

### ISSUE THREAD

**Issue by flutterpro** [DreamTeamMobile/Xamarin.Agora.Samples#8]
hello
we want use agora for video caudio in xamarin but agora is censored in our country . how can make call or videos behind of proxy / socks from app level ?

**Comment by alexsorokoletov** [comment]
@flutterpro, I would suggest talking to Agora support directly about that. 
Agora supports scenario when users are inside a firewall/behind proxy. Maybe that will help you. 

Agora’s support is definitely somebody you want to talk to. 

What is your country, just out of curiosity?
