### ISSUE TITLE
 Problem of having a local video using Agora Xamarin Forms

### ISSUE THREAD

**Issue by mayurlohite** [DreamTeamMobile/Xamarin.Agora.Samples#9]
Hi DreamTeam,

We are having a problem of having a local video using Agora Xamarin Forms.
We have followed your example to show a local video.
https://github.com/DreamTeamMobile/Xamarin.Agora.Samples
As you can see here:
In Xaml:
xmlns:agora="clr-namespace:Xamarin.Agora.Full.Forms;assembly=Xamarin.Agora.Full.Forms"
<agora:AgoraVideoView x:Name="LocalVideo" StreamUID="0" IsStatic="true" Mode="Adaptive" IsVideoMuted="false" IsVideoEnabled="true" IsEnabled="true"/>

Our agora service is as follows:

public AgoraManager(string appId)
        {
            _agoraService = AgoraService.Current;
            _agoraService.JoinChannelSuccess += (uid) => { };
            _agoraService.OnDisconnected += OnDisconnected;
            _agoraService.OnInfoUpdate += OnInfoUpdate;
            _agoraService.OnNewStream += OnNewStream;
            this.AgoraAppID = appId;
        }

We start session as follow:
_agoraService.StartSession(roomSessionID, AgoraAppID, null, webSdkInteroperability: true);

Note: we have tried with several Agora xamarin forms version: 2.9.0-beta04, 2.9.1

Do you know why?

**Comment by alexsorokoletov** [comment]
Hi @mayurlohite, sorry we're replying just now.
This repo is not tightly monitored.

If you still need help, what kind of problem do you have with the local video?

For all requests going forward it is better and faster to use Agora.io developer slack: https://docs.agora.io/en/Agora%20Platform/community

**Comment by DasVerma** [comment]
No video showing in xamarin forms

**Comment by alexsorokoletov** [comment]
@DasVerma please provide more information.
Screen recording + fork of this sample would be helpful so we can reproduce and address the issue.

We test the sample apps for each release.
